### ISSUE TITLE
openbmc pdbg can't access P9 cfam reg 0x2918

### ISSUE THREAD

**Issue by spinler** [open-power/pdbg#14]
We need to set bits 28 and 29 in P9 CFAM reg 0x2918 to get P9 to boot properly.  However, pdbg can't seem to access that register on a read or write:
```
# pdbg -a -b fsi -d p9w getcfam 0x2918
 getaddr: Error reading register
 No valid targets found or specified. Try adding -p/-c/-t options to specify a target.
 Alternatively run pdbg -a probe to get a list of all valid targets
```

What I want to put in the scripts is: pdbg ... putcfam 0x2918 0x0000000C 0x0000000C

Alistair has already been investigating this, but I was asked to open this issue so people can track it.

**Comment by apopple** [comment]
This should have been fixed by the below commit, so closing.

commit 4ce90bfe6ddfd4f7c8f76298a10a6f31a6e9cf7a
Author: Dinesh Chinari <chinari@us.ibm.com>
Date:   Wed Feb 22 14:12:11 2017 -0600

    Fix CFAM address computing for OpenFSI.
