### ISSUE TITLE
master doesn't build

### ISSUE THREAD

**Issue by eddiejames** [open-power/pdbg#19]
building with SDK or in openbmc.

$ ./bootstrap.sh

$ ./configure --host=arm (also tried with x86 sdk and host=x86, same problem).

$ make
objcopy -I binary -O elf32-littlearm -B arm fake.dtb.o fake.dtb.o
objcopy: architecture arm unknown
make[1]: *** [fake.dtb.o] Error 1
make[1]: Leaving directory `/home/eajames/devel/pdbg'
make: *** [all] Error 2

**Comment by apopple** [comment]
Fixing that hardcoded command (objcopy -I binary -O elf32-littlearm) in Makefile.am with something that actually detects the correct target architecture has been on my todo list for a while. For the moment I'm afraid the work around would be to change it to the correct arch.

**Comment by apopple** [comment]
Finally fixed as of pdbg-1.0. The correct arch should now be auto-detected, thanks for the report and let me know if you see any more problems!
