### ISSUE TITLE
[witherspoon VERSION="v1.99.5-67"] Using pdgb tool failed to getcfam values

### ISSUE THREAD

**Issue by SrideviRamesh** [open-power/pdbg#20]
Issue:
Using pdgb tool failed to getcfam values

System Info:
```
 cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.5-67"
VERSION_ID="v1.99.5-67-gcf7e849"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.5-67"
BUILD_ID="v1.99.5"
```

Procedure:

with latest pdgb tool on BMC execute commands mentioned below

```
./pdbg getcfam 2809 -p 0

./pdbg getcfam 2809 -p 0 -d p9w

```

Log Info:

```
root@witherspoon:~/pdgb_tool/bin# ./pdbg getcfam 2809 -p 0
pdbg: Failed to read from 0x00000be4 (0000000000000af9): Input/output error
getaddr: Error reading register

root@witherspoon:~/pdgb_tool/bin# ./pdbg getcfam 2809 -p 0 -d p9w
pdbg: Failed to read from 0x00000be4 (0000000000000af9): Input/output error
getaddr: Error reading register
```

please find attached ffdc , dmesg, journal logs

[20170524055935926487_MyFFDCLogs.zip](https://github.com/open-power/pdbg/files/1025327/20170524055935926487_MyFFDCLogs.zip)
[journalctl_logs.txt](https://github.com/open-power/pdbg/files/1025329/journalctl_logs.txt)
[dmesg_logs.txt](https://github.com/open-power/pdbg/files/1025330/dmesg_logs.txt)

**Comment by lkammath** [comment]
Sorry my mistake. It works

root@witherspoon:~/pdgb_tool/bin# ./pdbg getcfam 0x2809 -p 0 -d p9w
p0:0x2809: 0x0000000085405083

**Comment by lkammath** [comment]
We can close this
