### ISSUE TITLE
ram_instructions bug?

### ISSUE THREAD

**Issue by hlandau** [open-power/pdbg#24]
Shouldn't it be `opcode = mfspr(1, 277)` here?

https://github.com/open-power/pdbg/blob/master/libpdbg/chip.c#L161

**Comment by cyrilbur-ibm** [comment]
Hi Hlandau,
Possibly, although I have a few other concerns there. Thanks for bringing this to my attention, I'll have a deeper look.

**Comment by apopple** [comment]
Thanks @hlandau for reporting and @cyrilbur-ibm for submitting the fix.
